### PR TITLE
changes to make things more clear

### PR DESCRIPTION
**Pull request by nsteinme**
- Updated text at top to emphasize the more common way of accessing the GUI. 
- Expanded description of intended workflow. 
- Clarified usage of ctrl+h

### CODE REVIEW

**Comment by rossant** [comment]
thanks! looks good. Could you just rename to `shortcut-keys.md` for consistency?

some time we should automate the creation of the shortcut keys page so that it is updated when the shortcuts are changed (part of the doc build process)

**Comment by nippoo** [comment]
great, thanks Nick! couple of quick suggestions:
- this new file will need to be added in the mkdocs.yml in the root directory otherwise it won't appear. :)
- there are a couple of blank lines at the end of the shortcut-keys.md file.
- also, tbh, I'd rename to shortcuts.md, since it also includes mouse clicks/drags/buttons which aren't strictly speaking keys. but that's very minor and I don't really have a strong view)

**Comment by rossant** [comment]
> I'd rename to shortcuts.md

+1

**Comment by nsteinme** [comment]
It is accessible via link from manual-clustering.md - actually if someone
could make sure the link is correct that would be great, I tried to copy
how another link worked but I'm not certain I got it right.

**Comment by nsteinme** [comment]
k, done all those things

**Comment by nippoo** [comment]
Great! You all done - happy to merge? If so I'm happy.

**Comment by nsteinme** [comment]
yep, think so

**Pull request merged**
